### ISSUE TITLE
custom config parameters not loaded

### ISSUE THREAD

**Issue by MatthewReed** [whiteoctober/WhiteOctoberTCPDFBundle#25]
Your WhiteOctoberTCPDFBundle class defines only "k_" prefixed constants like "k_path_cache" and "pdf_font_name_main" constant.
Any other common parameter like "pdf_author" or "pdf_creator", while it's defined in Configuration, is not defined as a constant.
Maybe logic should be changed in WhiteOctoberTCPDFBundle rows 27 - 42.

Best regards
Matteo Rossi

**Comment by sampart** [comment]
We should add an answer to https://stackoverflow.com/questions/13235808/change-whiteoctober-tcpdf-bundle-configuration-values once this has been resolved.

**Comment by sampart** [comment]
Fixed in release [1.1.0](https://github.com/whiteoctober/WhiteOctoberTCPDFBundle/releases/tag/1.1.0).
