### ISSUE TITLE
Package tecnick.com/tcpdf is abandoned / new version needed

### ISSUE THREAD

**Issue by mkilmanas** [whiteoctober/WhiteOctoberTCPDFBundle#36]
I see you have already changed `tecnick.com/tcpdf` to `tecnick/tcpdf` in master branch, but this change did not get it's own version tag, so it cannot yet be pulled via composer, and thus composer complains:
```
Package tecnick.com/tcpdf is abandoned, you should avoid using it. Use tecnickcom/tcpdf instead.
```
Could you please tag the latest version with a number

**Comment by richsage** [comment]
Added tag 1.0.2 :-)

**Comment by mkilmanas** [comment]
Thanks, that what :zap: fast!
