### ISSUE TITLE
phpStorm custom class auto completion

### ISSUE THREAD

**Issue by rogatec** [whiteoctober/WhiteOctoberTCPDFBundle#37]
Hi,

does anyone know how _PhpStorm_ can detect, that I've included a custom class for this bundle?

My custom methods aren't detected automatically, which is quite annoying.
The create method from the bundle returns explicit a TCPDF object, which is in fact correct, but it doesn't get the inheritance relation ;-(

Any hints are very appreciated!

**Comment by sampart** [comment]
Could you use an `@var` annotation on the relevant variable?  That tells IDEs what type the variable is.

For example:

    /* @var MyCustomClass $myPDFObj */
    $myPDFObj = $container->get("white_october.tcpdf")->create();

Hope this helps!

**Comment by rogatec** [comment]
Well... Yes of course this works... My bad I didn't thought about that.

Thank you!
