### ISSUE TITLE
Compile Error: Cannot redeclare class TCPDF

### ISSUE THREAD

**Issue by YulianD** [whiteoctober/WhiteOctoberTCPDFBundle#38]
Compile Error: Cannot redeclare class TCPDF
`Stack Trace
in vendor\tecnickcom\tcpdf\tcpdf.php at line 134   -
- @version 6.2.8
- @author Nicola Asuni - info@tecnick.com
  */
  class TCPDF {
  // Protected properties
  `

**Comment by sampart** [comment]
Hi @YulianD,

It sounds like you're trying to use both the WhiteOctoberTCPDFBundle and https://github.com/tecnickcom/TCPDF (check your `composer.json` and you'll probably see both listed).

I think you'll just have to pick one of the two to avoid this error!

Thanks
Sam
