### ISSUE TITLE
Error tempnam when insertint image inside twig

### ISSUE THREAD

**Issue by braianj** [whiteoctober/WhiteOctoberTCPDFBundle#43]
Hello, when I try to create a PDF with an image in it, I get this

> Notice: tempnam(): file created in the system's temporary directory

The image inside the twig is added as 

`<img src="{{ asset('img/image.png') }}">`

Please help

**Comment by sampart** [comment]
If you have time, please do let us know how you sorted this one, @braianj; others might find it useful to know.  Thanks

**Comment by braianj** [comment]
it was a problem with my host file, nothing with the code to share

**Comment by sampart** [comment]
Thanks for clarifying :+1:
