### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by sampart** [whiteoctober/WhiteOctoberTCPDFBundle#57]
Hi,

Sam here, one of the current maintainers of this project.

Given that we no longer use PHP in any of our active projects, it's becoming harder to give this plugin the time it needs.

Therefore, we're looking for new maintainer(s) for this project.

We'd like any new prospective maintainer to fork this project, and then once that fork has moved forward enough to give us confidence in your ownership, we would link to your fork prominently from the top of the README here, encouraging others to use it instead.

If you're interested, please go ahead and fork (if you haven't already) and start work!  If you've forked and would like others to help you, feel free to reply in this issue with details of your fork.

Please do reply here if you have questions.  Thanks in anticipation.

**Comment by sampart** [comment]
@davnavarro has made a Symfony >= 3,4 fork of this project here: https://github.com/Qipsius/QipsiusTCPDFBundle  Thank you, David!

**Comment by sampart** [comment]
@davnavarro At some point, the `whiteoctober` organisation will be deleted, along with this repo. Before that point, your repo - which is currently a fork of this one - will be updated to become the "root" (parent) repository. There's nothing you need to do - this is just FYI - but do let me know if you have any questions. Thanks again for your maintainership.

**Comment by davnavarro** [comment]
Ok @sampart, thanks for your notice.

**Comment by sampart** [comment]
On reflection, I'll actually move this repo somewhere else (and archive it) and update Packagist to point there, since this project in Packagist is still getting a lot of installs.

**Comment by davnavarro** [comment]
I think it's a good idea, Qipsisus branch does not work in older Symfony versions

**Comment by sampart** [comment]
I've transferred this now.
