### ISSUE TITLE
Symfony env variable

### ISSUE THREAD

**Issue by DarkoKlisuric** [whiteoctober/WhiteOctoberTCPDFBundle#59]
Hello!

Symfony 5.* has no longer have %kernel.root_dir%. 

When I change this 

->scalarNode('file')->defaultValue('**%kernel.root_dir%**/../vendor/tecnickcom/tcpdf/tcpdf.php')->end()

in this 

->scalarNode('file')->defaultValue('**%kernel.project_dir%**/vendor/tecnickcom/tcpdf/tcpdf.php')->end()

and others "%kernel.root_dir%" variables, works perfectly.

Thanks!

**Comment by davnavarro** [comment]
Hi DarkoKlisuric,

This may interest you: https://github.com/whiteoctober/WhiteOctoberTCPDFBundle/pull/58/commits

;)

**Comment by DarkoKlisuric** [comment]
Thank you very much davnavarro :)
